HASH_FIELDS = (
    'LMI_MERCHANT_ID',
    'LMI_PAYMENT_NO',
    'LMI_SYS_PAYMENT_ID',
    'LMI_SYS_PAYMENT_DATE',
    'LMI_PAYMENT_AMOUNT',
    'LMI_CURRENCY',
    'LMI_PAID_AMOUNT',
    'LMI_PAID_CURRENCY',
    'LMI_PAYMENT_SYSTEM',
    'LMI_SIM_MODE'
)

HASH_METHOD = 'md5'
HASH_FAIL_HTTP_CODE = 200



